apiVersion: v1
kind: Service
metadata:
  name: versionapp
  labels:
    app.kubernetes.io/name: {{ include "versionapp.name" . }}
    helm.sh/chart: {{ include "versionapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIp
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "versionapp.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
